# deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-container
        image: mlopsacrjessica.azurecr.io/iris-infer:v1
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  selector:
    app: iris-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
